GET http://localhost:5025/games

###
GET http://localhost:5025/games/65427fc2-daf9-44c9-a32a-d6f12a1fe0c5

###
POST http://localhost:5025/games
Content-Type: application/json

{
    "name": "TEST GAME",
    "genreId": "E36EFC58-CB6B-4D21-B979-7752F9EC7DD1",
    "price": 19.99,
    "releaseDate": "1992-07-05",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sollicitudin, ante sed tempor luctus, eros mi vehicula eros, at dictum lectus massa sit amet sem. Integer vestibulum sodales urna, ut condimentum magna."
}

###
PUT http://localhost:5025/games/DCB17722-B350-4B9A-B8A5-0D4A10B1E757
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genreId": "f22f896f-c399-4b66-ad69-04cfed1a2c87",
    "price": 9.99,
    "releaseDate": "1992-07-05",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sollicitudin, ante sed tempor luctus, eros mi vehicula eros, at dictum lectus massa sit amet sem. Integer vestibulum sodales urna, ut condimentum magna."
}

###
DELETE http://localhost:5025/games/16c5cd5e-7f12-44a5-8bb0-eb27cee5d629

###
GET http://localhost:5025/genres