GET http://localhost:5025/games

###
GET http://localhost:5025/games/766967b5-8e22-42b4-9854-96900d8af041

###
POST http://localhost:5025/games
Content-Type: application/json

{
    "name": "Minecraft II4",
    "genreId": "0ca91115-8bb0-445b-bd6d-13732d36b9f9",
    "price": 19.99,
    "releaseDate": "2011-11-18",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sollicitudin, ante sed tempor luctus, eros mi vehicula eros, at dictum lectus massa sit amet sem. Integer vestibulum sodales urna, ut condimentum magna."
}

###
PUT http://localhost:5025/games/6bb95c42-472c-4051-8e58-573b940ad156
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genreId": "f22f896f-c399-4b66-ad69-04cfed1a2c87",
    "price": 9.99,
    "releaseDate": "1992-07-05",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sollicitudin, ante sed tempor luctus, eros mi vehicula eros, at dictum lectus massa sit amet sem. Integer vestibulum sodales urna, ut condimentum magna."
}

###
DELETE http://localhost:5025/games/3da04533-8da7-4f7f-9efb-00396ec940e5

###
GET http://localhost:5025/genres